# Generated by Django 2.1.1 on 2018-09-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('category_en', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=60)),
                ('page_desc', models.CharField(max_length=160)),
                ('page_keywords', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField(blank=True)),
                ('img', models.CharField(blank=True, max_length=300)),
                ('img_alt', models.CharField(max_length=100)),
                ('vid', models.CharField(blank=True, max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('desc', models.TextField(blank=True)),
                ('img', models.CharField(blank=True, max_length=300)),
                ('img_alt', models.CharField(blank=True, max_length=100)),
                ('vid', models.CharField(blank=True, max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Post')),
            ],
        ),
    ]
